name: Python CI

on:
  push:
      branches: [main]

job:
    build:
          runs-on: ubuntu-latest

          steps:
          - uses: actions/checkout@v2
          - name: Set Up Python
            uses: actions/setup-python@v2
            with:
                python-version: '3.x'
          - name: Run Tests
            ruu: python -m unittest discover